#!/usr/bin/env python3
"""Install Git hooks for TinyPage project."""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path


def make_executable(path: Path) -> None:
    """Make a file executable."""
    current = path.stat().st_mode
    path.chmod(current | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)


def install_hook(hooks_dir: Path, hook_name: str, source: Path) -> bool:
    """Install a single hook."""
    hook_path = hooks_dir / hook_name
    try:
        with open(source, "r", encoding="utf-8") as src:
            content = src.read()

        shebang = "#!/bin/sh\n"
        if sys.platform == "win32":
            shebang = f"#!/usr/bin/env python\n"

        with open(hook_path, "w", encoding="utf-8") as dst:
            dst.write(shebang)
            dst.write(f'# Auto-generated by TinyPage - do not edit directly\n')
            dst.write(f'# Source: {source}\n\n')
            dst.write(content)

        make_executable(hook_path)
        print(f"[HOOK] Installed: {hook_name}")
        return True
    except Exception as e:
        print(f"[HOOK] Failed to install {hook_name}: {e}")
        return False


def main() -> int:
    """Install Git hooks."""
    project_root = Path(__file__).resolve().parent.parent.parent
    hooks_source_dir = project_root / "scripts" / "git-hooks"
    git_dir = project_root / ".git"

    if not git_dir.exists():
        print("[HOOK] Error: Not a Git repository (no .git directory)")
        print("[HOOK] Run 'git init' first")
        return 1

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    pre_commit_source = hooks_source_dir / "pre-commit"
    pre_push_source = hooks_source_dir / "pre-push"

    if pre_commit_source.exists():
        install_hook(hooks_dir, "pre-commit", pre_commit_source)
    else:
        print(f"[HOOK] Warning: pre-commit source not found: {pre_commit_source}")

    if pre_push_source.exists():
        install_hook(hooks_dir, "pre-push", pre_push_source)
    else:
        print(f"[HOOK] Warning: pre-push source not found: {pre_push_source}")

    print("[HOOK] Git hooks installation complete")
    return 0


if __name__ == "__main__":
    sys.exit(main())